apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uy5d0gdd8-nodejs 
  janus-idp.io/tekton: uy5d0gdd8-nodejs
  backstage.io/kubernetes-id: uy5d0gdd8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uy5d0gdd8-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  